export const MARKER_CATEGORIES = [
  "HOSPITAL",
  "PHARMACY",
  "GAS_STATION",
  "POLICE_STATION",
  "FIRE_STATION",
  "SUPERMARKET",
  "PUBLIC_TRANSPORT_HUB",
  "CITY_DISTRICT_OFFICE",
  "COMMUNITY_CENTER",
  "SCHOOL",
  "ELDERLY_CARE",
  "EMERGENCY_SUPPORT_POINT"
] as const;

export type MarkerCategory = typeof MARKER_CATEGORIES[number];
